### ISSUE TITLE
查成分报错，没有返回结果

### ISSUE THREAD

**Issue by ChthollyWn** [yajiwa/zhenxun_plugin_ddcheck#4]
bot后台报错信息
![14SI2@70YR{1$9TA)1_S_)0](https://user-images.githubusercontent.com/85938618/170418367-f1d69dbe-d98e-4263-b3b1-268b436bd815.png)

**Comment by yajiwa** [comment]
上面写的很清楚了，请参考go-cqhttp输出，这个消息大概率被风控了，别问解决方法，风控问题收购腾讯

**Comment by ChthollyWn** [comment]
> 

go-cq输出结果如下
![N06H{O9 0HPRNG_} U@~%4F](https://user-images.githubusercontent.com/85938618/170419018-2ebf8206-dd5d-4774-b141-478d5b5ed284.png)
请问被风控一般不是会提示吗，而且这个是私聊的，私聊消息也会被风控吗？求解答，多谢

**Comment by yajiwa** [comment]
任何消息都可能被风控

**Comment by yajiwa** [comment]
试试换个人，感觉你资源没下载成功

**Comment by ChthollyWn** [comment]
> 试试换个人，感觉你资源没下载成功

我重新换了人也是这个结果，然后资源包删除后重新安装了插件和依赖，依旧是这个问题，请问有解决方法嘛呜呜呜

**Comment by yajiwa** [comment]
看看这个data\ddcheck文件夹下两个文件里是否有东西，如果都有的话那就无解了

**Comment by ChthollyWn** [comment]
> 看看这个data\ddcheck文件夹下两个文件里是否有东西，如果都有的话那就无解了

我看了一下，html和json里都有代码，是不是寄了
