### ISSUE TITLE
填了B站用户的Cookie没显示主播牌子

### ISSUE THREAD

**Issue by SPLUS-VABLE** [yajiwa/zhenxun_plugin_ddcheck#6]
![image](https://user-images.githubusercontent.com/42440354/170818757-33915820-1699-487f-8405-d7cd4b618a4d.png)

![image](https://user-images.githubusercontent.com/42440354/170818748-bb438ee3-548a-4a3e-a58a-218e44654b4b.png)

**Comment by ChrisYan6** [comment]
+1，用cookie调用api时返回值有牌子，成分姬生成的图片里没有。

**Comment by ChrisYan6** [comment]
后续，把get https:// https://www.bilibili.com/
请求标头里的coockie全部复制过去就行了
